"""add worker_id to reply_thread_locks

Revision ID: 099be33742b7
Revises: f9bf7b7a6b18
Create Date: 2026-02-16 16:23:06.587010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '099be33742b7'
down_revision: Union[str, Sequence[str], None] = 'f9bf7b7a6b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_thread_locks', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.alter_column('reply_thread_locks', 'bucket_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply_thread_locks', 'bucket_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('reply_thread_locks', 'worker_id')
    # ### end Alembic commands ###
