"""add credits usage locks

Revision ID: 25083a477f5c
Revises: cc229af53430
Create Date: 2026-02-16 16:03:23.378239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25083a477f5c'
down_revision: Union[str, Sequence[str], None] = 'cc229af53430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_audit', sa.Column('references_header', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_conversation_audit_created_at'), table_name='conversation_audit')
    op.drop_index(op.f('ix_conversation_audit_org_thread_created'), table_name='conversation_audit')
    op.drop_column('conversation_audit', 'references')
    op.drop_constraint(op.f('email_accounts_org_id_fkey'), 'email_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'email_accounts', 'organizations', ['org_id'], ['id'])
    op.alter_column('organizations', 'auto_reply',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('organizations', 'max_replies_per_hour',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_constraint(op.f('users_org_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_org_id_fkey'), 'users', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.alter_column('organizations', 'max_replies_per_hour',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('organizations', 'auto_reply',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'email_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('email_accounts_org_id_fkey'), 'email_accounts', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.add_column('conversation_audit', sa.Column('references', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_conversation_audit_org_thread_created'), 'conversation_audit', ['org_id', 'thread_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_audit_created_at'), 'conversation_audit', ['created_at'], unique=False)
    op.drop_column('conversation_audit', 'references_header')
    # ### end Alembic commands ###
