"""add org credits usage locks tables

Revision ID: 5adf5498e0a0
Revises: 25083a477f5c
Create Date: 2026-02-16 16:07:30.751444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5adf5498e0a0'
down_revision: Union[str, Sequence[str], None] = '25083a477f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_credits_org_id'), 'org_credits', ['org_id'], unique=True)
    op.create_table('org_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_usage_created_at'), 'org_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_usage_event'), 'org_usage', ['event'], unique=False)
    op.create_index(op.f('ix_org_usage_org_id'), 'org_usage', ['org_id'], unique=False)
    op.create_table('reply_thread_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('thread_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'thread_key', name='uq_reply_thread_locks_org_thread')
    )
    op.create_index(op.f('ix_reply_thread_locks_created_at'), 'reply_thread_locks', ['created_at'], unique=False)
    op.create_index(op.f('ix_reply_thread_locks_org_id'), 'reply_thread_locks', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_thread_locks_org_id'), table_name='reply_thread_locks')
    op.drop_index(op.f('ix_reply_thread_locks_created_at'), table_name='reply_thread_locks')
    op.drop_table('reply_thread_locks')
    op.drop_index(op.f('ix_org_usage_org_id'), table_name='org_usage')
    op.drop_index(op.f('ix_org_usage_event'), table_name='org_usage')
    op.drop_index(op.f('ix_org_usage_created_at'), table_name='org_usage')
    op.drop_table('org_usage')
    op.drop_index(op.f('ix_org_credits_org_id'), table_name='org_credits')
    op.drop_table('org_credits')
    # ### end Alembic commands ###
