"""align org_credits schema

Revision ID: d01b6b0b8c4d
Revises: db6ad21fb3c2
Create Date: 2026-02-16 16:18:20.117507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01b6b0b8c4d'
down_revision: Union[str, Sequence[str], None] = 'db6ad21fb3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_credits', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('org_credits', sa.Column('credits_total', sa.Integer(), nullable=False))
    op.add_column('org_credits', sa.Column('credits_used', sa.Integer(), nullable=False))
    op.add_column('org_credits', sa.Column('credits_reset_at', sa.Date(), nullable=True))
    op.drop_column('org_credits', 'credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_credits', sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('org_credits', 'credits_reset_at')
    op.drop_column('org_credits', 'credits_used')
    op.drop_column('org_credits', 'credits_total')
    op.drop_column('org_credits', 'plan')
    # ### end Alembic commands ###
