"""add website_url to organizations

Revision ID: db6ad21fb3c2
Revises: 5adf5498e0a0
Create Date: 2026-02-16 16:14:44.695116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6ad21fb3c2'
down_revision: Union[str, Sequence[str], None] = '5adf5498e0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website_url')
    # ### end Alembic commands ###
