"""add bucket_start to reply_thread_locks

Revision ID: f9bf7b7a6b18
Revises: d01b6b0b8c4d
Create Date: 2026-02-16 16:19:50.820579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9bf7b7a6b18'
down_revision: Union[str, Sequence[str], None] = 'd01b6b0b8c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_thread_locks', sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply_thread_locks', 'bucket_start')
    # ### end Alembic commands ###
